modLoader="javafml"
loaderVersion="[51,)"
license="All rights reserved"
[[mods]]
modId="luckytntmod"
version="6.0"
displayName="Lucky TNT Mod"
logoFile="logo.png"
credits="Created by SlimingHD and Fleshcrafter"
description='''
Lucky TNT adds tons of new TNT to destroy your world with!
'''
[[dependencies.luckytntmod]]
    modId="forge"
    mandatory=true
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntmod]]
	modId="luckytntlib"
	mandatory=true
	versionRange="[51.0.21.0,)"
	ordering="NONE"
	side="BOTH"
