modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
[[mods]]
modId="luckytntmod"
version="44.1.2.4"
displayName="Lucky TNT Mod"
logoFile="logo.png"
credits="Created by SlimingHD and Fleshcrafter"
description='''
Lucky TNT adds tons of new TNT to destroy your world with!
'''
[[dependencies.luckytntmod]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luckytntmod]]
	modId="luckytntlib"
	mandatory=true
	versionRange="[44.1.2.4, 44.1.2.5)"
	ordering="NONE"
	side="BOTH"
